from domain.Domain import Domain
from factories.PointSourceFactory import PointSourceFactory
from visuals.Visualizer import Visualizer

def main():
    """
    Main function to set up the domain, create and place a point source, 
    calculate electric field and potential, and visualize the results.
    """
    # Initialize the domain with dimensions 100x100 and other parameters
    demo_domain = Domain(100, 100, 50, 50)

    # Define the placement data for the source
    placement_data = {'x': -10, 'y': 20}

    # Create a factory for point sources
    factory = PointSourceFactory()

    # Create a placeable source with a specified parameter
    source = factory.create_placeable_source(10)
    
    # Place the source in the domain using the placement data
    source.place(placement_data)

    # Add the source to the domain with a given name
    demo_domain.add_a_source(source, 'source 1')

    # Calculate the electric field vector field generated by the source
    vector_field = demo_domain.get_efield(source, demo_domain.main_coords)
    
    # Calculate the electric potential scalar field generated by the source
    scalar_field = demo_domain.get_epotential(source, demo_domain.main_coords)

    # Initialize the visualizer with the domain
    visualizer = Visualizer(demo_domain)
    
    # Place the source in the visualizer for accurate representation
    visualizer.place_source(source)

    # Plot the scalar field as a heatmap
    visualizer.plot_scalar_field(scalar_field._field, 'heatmap')
    
    # Plot the vector field as a quiver plot
    visualizer.plot_vector_field(vector_field._field, 'quiver')

    # Show the visualizations
    visualizer.show()

# Run the main function
main()


