name: E-Field Workflows
run-name: ${{ github.actor }} is merging a pull request
on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python Version 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Test with basic tests
        run: |
          pip install pytest pytest
          pip install numpy
          pytest tests/tests.py