name: E-Field Workflows
run-name: ${{ github.actor }} is creating a pull request
on:
  pull_request:
    branches:
    - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python Version 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Test with Unit Tests
        run: |
          pip install pytest pytest
          pip install numpy
          pip install scipy
          pip install matplotlib
          export PYTHONPATH="$PWD"
          pytest tests/